version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: group15_database
      MYSQL_USER: group15
      MYSQL_PASSWORD: group15password
      MYSQL_ROOT_PASSWORD: group15password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - common-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: group15password
    ports:
      - '8080:80'
    networks:
      - common-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=group15_database
      - MONGO_INITDB_ROOT_PASSWORD=group15
    expose:
      - 27018
    networks:
      - common-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  db_data:
