version: '3.5'

services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${MYSQL_USER:-mysqluser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysqlpassword}
    volumes:
       - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    restart: unless-stopped

  mongo:
    container_name: mongo_container
    image: mongo:latest
    volumes:
       - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    restart: unless-stopped

networks:
  mysql_network:
    driver: bridge
  mongo_network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
